Repository the-bugs/medcheck-backend-rails, pull requests merged in 2023-11, with the labels that each got.

#1 Feat/user scaffold
  .gitignore
  Gemfile.lock
  app/controllers/users_controller.rb
  app/models/user.rb
  config/routes.rb
  db/migrate/20231108173611_create_users.rb
  test/controllers/users_controller_test.rb
  test/fixtures/users.yml
  test/models/user_test.rb
Labels: back end Ruby, feature

#4 User Authentication
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/authentication_controller.rb
  app/controllers/users_controller.rb
  app/lib/json_web_token.rb
  app/models/user.rb
  config/routes.rb
  db/migrate/20231114012007_add_password_digest_to_users.rb
  db/schema.rb
  test/controllers/authentication_controller_test.rb
Labels: back end Ruby, wip

#20 Restrict Specialty creation to the admin role
  app/controllers/application_controller.rb
  app/controllers/specialties_controller.rb
  app/models/user.rb
  db/schema.rb
Labels: wip
